const test=require('node:test'),assert=require('node:assert/strict');
const {classifyCarrier,csvCell,leadsCsv}=require('../src/sales/carriers');
const {encrypt,decrypt}=require('../src/sales/secrets');
const {retryDelay}=require('../src/sales/worker');
const good={entity_type:'CARRIER',legal_name:'Fixture Freight',physical_address:'5 Hillcrest Dr Downingtown, PA 19335',operating_status:'AUTHORIZED FOR Property',mc_mx_ff_numbers:'MC-123456',usdot:'98765',power_units:4,drivers:3,cargo_carried:['General Freight'],operation_classification:['Auth. For Hire']};
test('accepts US authorized freight without inventing email or equipment',()=>{const r=classifyCarrier(good,123456);assert.equal(r.outcome,'ACCEPTED');assert.equal(r.details.email,'');assert.match(r.details.equipment,/Unknown/);assert.equal(r.details.powerUnits,4);});
test('excludes mixed garbage/hay/agricultural cargo and unauthorized carriers',()=>{for(const cargo of ['Garbage/Refuse','Hay','Agricultural Supplies','Grain, Feed, Hay','Livestock'])assert.equal(classifyCarrier({...good,cargo_carried:['General Freight',cargo]},123456).outcome,'EXCLUDED');for(const operating_status of ['NOT AUTHORIZED','INACTIVE','OUT OF SERVICE'])assert.equal(classifyCarrier({...good,operating_status},123456).outcome,'EXCLUDED');});
test('uncertain carrier information goes to review',()=>{for(const change of [{mc_mx_ff_numbers:'MC-654321'},{physical_address:'Unknown'},{cargo_carried:[]},{usdot:null},{operating_status:'UNKNOWN'}])assert.equal(classifyCarrier({...good,...change},123456).outcome,'REVIEW');assert.equal(classifyCarrier({...good,country:'CA'},123456).outcome,'EXCLUDED');assert.equal(classifyCarrier({...good,power_units:0},123456).outcome,'EXCLUDED');assert.throws(()=>classifyCarrier({error:'bad'},123456));});
test('CSV preserves commas/quotes and prevents formulas',()=>{assert.equal(csvCell('hello,"world"'),'"hello,""world"""');assert.equal(csvCell('=1+1'),'"\'=1+1"');const d=classifyCarrier(good,123456).details;const csv=leadsCsv([{...d,details:d,fetchedAt:new Date('2026-01-01'),status:'NEW',contactCount:0,notes:'=CMD()'}]);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes('Reported power units'));assert.ok(csv.includes("'=CMD()"));});
test('keys use authenticated encryption',()=>{process.env.SALES_ENCRYPTION_KEY='synthetic-test-encryption-secret';const value='synthetic-test-api-key';const a=encrypt(value),b=encrypt(value);assert.notEqual(a,b);assert.ok(!a.includes(value));assert.equal(decrypt(a),value);const pieces=a.split('.');pieces[1]=Buffer.alloc(16).toString('base64');assert.throws(()=>decrypt(pieces.join('.')));delete process.env.SALES_ENCRYPTION_KEY;});
test('respects provider retry delays',()=>{assert.equal(retryDelay('30'),30000);assert.equal(retryDelay('Thu, 01 Jan 2026 00:01:00 GMT',Date.parse('2026-01-01T00:00:00Z')),60000);assert.equal(retryDelay('nonsense'),0);});
test('transient failures and rate limits never require manual resume after five attempts',()=>{const {retryPlan}=require('../src/sales/worker');for(const n of [0,4,10,100]){const plan=retryPlan({retryable:true},'reading provider response',n,0);assert.equal(plan.blocked,false);assert.ok(plan.delay<=900000);}const rate=retryPlan({delay:3600000},'requesting provider',9,0);assert.equal(rate.blocked,false);assert.equal(rate.delay,3600000);assert.equal(retryPlan({name:'AbortError'},'reading provider response',10).blocked,false);assert.equal(retryPlan({code:'P2028'},'saving carrier',10).blocked,false);});
test('parser bug is quarantined after three attempts; unknown request errors are not skipped',()=>{const {retryPlan,failedSnapshot}=require('../src/sales/worker');assert.equal(retryPlan({quarantine:true},'reading provider response',1).quarantine,false);assert.equal(retryPlan({quarantine:true},'reading provider response',2).quarantine,true);assert.equal(retryPlan({},'reading provider response',4).blocked,true);const r=failedSnapshot(2045);assert.equal(r.outcome,'REVIEW');assert.equal(r.details.mc,2045);assert.deepEqual(r.details.cargo,[]);});

test('missing legal name does not block a genuine unauthorized snapshot',async()=>{const {decodeSnapshot}=require('../src/sales/provider');const raw={...good,legal_name:null,operating_status:'NOT AUTHORIZED',mc_mx_ff_numbers:'MC-8882',usdot:'2968751'};const r=await decodeSnapshot(new Response(JSON.stringify(raw)),8882);assert.equal(r.outcome,'EXCLUDED');assert.equal(r.reason,'Not authorized or out of service');assert.equal(r.details.mc,8882);});
test('otherwise eligible carriers without names are retained for review, never accepted',()=>{for(const legal_name of [null,'','  ',undefined]){const r=classifyCarrier({...good,legal_name},123456);assert.equal(r.outcome,'REVIEW');assert.equal(r.reason,'Company legal name missing from provider snapshot');assert.equal(r.details.mc,123456);assert.equal(r.details.usdot,good.usdot);}assert.equal(classifyCarrier({...good,legal_name:null,cargo_carried:['Garbage/Refuse']},123456).outcome,'EXCLUDED');});
test('nameless API errors and mismatched records still cannot advance the checkpoint',()=>{for(const raw of [{message:'upstream error'},{legal_name:null},{...good,legal_name:null,usdot:null},{...good,legal_name:null,mc_mx_ff_numbers:'MC-654321'}])assert.throws(()=>classifyCarrier(raw,123456),/UNRECOGNIZED_RESPONSE/);});
