const {randomUUID}=require('node:crypto');
const {validateTemplate}=require('./messageTemplate');
const { encrypt } = require('./secrets');
const { leadsCsv } = require('./carriers');
const statuses = ['NEW','CONTACTED','INTERESTED','FOLLOW_UP','NOT_INTERESTED'];
function fail(status,message){const e=new Error(message);e.status=status;throw e;}
function id(v){const n=Number(v);if(!Number.isSafeInteger(n)||n<1||n>99999999)fail(400,'Enter a valid positive number.');return n;}
function apiKey(v){if(typeof v!=='string'||v.trim().length<8||v.length>512||/[\r\n]/.test(v))fail(400,'Enter a valid API key.');return encrypt(v.trim());}
function jobView({encryptedKey,...row}){return {...row,hasKey:!!encryptedKey};}
function createSalesService(db){
 async function active(tx,branchId){const b=await tx.branch.findUnique({where:{id:id(branchId)}});if(!b)fail(404,'Branch not found.');if(!b.isActive)fail(409,'Historical branches are read-only.');}
 async function find(tx,model,record,branchId){const row=await tx[model].findFirst({where:{id:id(record),...(model==='salesList'?{job:{branchId:id(branchId)}}:{branchId:id(branchId)})}});if(!row)fail(404,'Record not found in this branch.');return row;}
 return {
 async exportPreference(branchId){const branch=await db.branch.findUnique({where:{id:id(branchId)}});if(!branch)fail(404,'Branch not found.');return await db.salesExportPreference.findUnique({where:{branchId:branch.id}})||{messageTemplate:'',enabled:false};},
 async saveExportPreference(branchId,body){await active(db,branchId);if(typeof body.enabled!=='boolean')fail(400,'Choose whether to include messages.');const messageTemplate=validateTemplate(body.messageTemplate);return db.salesExportPreference.upsert({where:{branchId:id(branchId)},create:{branchId:id(branchId),messageTemplate,enabled:body.enabled},update:{messageTemplate,enabled:body.enabled,updatedAt:new Date()}});},
 async contactList(record,branchId,user,requestId){
 if(typeof requestId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(requestId))fail(400,'Invalid list contact action ID.');
 return db.$transaction(async tx=>{
 await active(tx,branchId);const list=await find(tx,'salesList',record,branchId);
 await tx.$queryRawUnsafe('SELECT "id" FROM "SalesList" WHERE "id"=$1 FOR UPDATE',list.id);
 const prior=await tx.salesListContactBatch.findUnique({where:{id:requestId}});
 if(prior){if(prior.listId!==list.id||prior.userId!==user.id)fail(409,'Contact action already belongs to another list or user.');return prior;}
 const leads=await tx.$queryRawUnsafe('SELECT "id" FROM "SalesLead" WHERE "listId"=$1 ORDER BY "id" FOR UPDATE',list.id);
 const now=new Date();
 if(leads.length){await tx.salesContact.createMany({data:leads.map(lead=>({id:randomUUID(),leadId:lead.id,userId:user.id,userName:user.name||'Staff',createdAt:now}))});await tx.salesLead.updateMany({where:{id:{in:leads.map(l=>l.id)}},data:{contactCount:{increment:1},lastContactAt:now,revision:{increment:1}}});}
 return tx.salesListContactBatch.create({data:{id:requestId,listId:list.id,userId:user.id,leadCount:leads.length}});
 },{timeout:30000});
 },
 async dashboard(branchId,jobPage=1,listPage=1){branchId=id(branchId);jobPage=id(jobPage);listPage=id(listPage);const where={branchId};const [jobs,lists,worker,jobCount,listCount,stats]=await Promise.all([db.salesJob.findMany({where,orderBy:{id:'desc'},take:20,skip:(jobPage-1)*20}),db.salesList.findMany({where:{job:{branchId}},include:{_count:{select:{contactBatches:true}}},orderBy:{id:'desc'},take:20,skip:(listPage-1)*20}),db.salesWorker.findUnique({where:{id:'main'},select:{hosted:true,heartbeatAt:true,schedulerAt:true}}),db.salesJob.count({where}),db.salesList.count({where:{job:{branchId}}}),db.salesJob.aggregate({where,_sum:{processed:true,accepted:true,excluded:true,missing:true,needsReview:true,duplicates:true}})]);return {jobs:jobs.map(jobView),lists,worker:worker?{...worker,online:!!worker.schedulerAt&&Date.now()-worker.schedulerAt.getTime()<60000}:null,jobCount,listCount,totals:stats._sum};},
 async create(body,user){const branchId=id(body.branchId),startMc=id(body.startMc),endMc=id(body.endMc);if(endMc<startMc||endMc-startMc>=1000000)fail(400,'Choose a range of up to 1,000,000 MC numbers.');const encryptedKey=apiKey(body.apiKey);return db.$transaction(async tx=>{await active(tx,branchId);return jobView(await tx.salesJob.create({data:{branchId,startMc,endMc,nextMc:startMc,encryptedKey,createdBy:user.id}}));});},
 async control(record,branchId,action,body={}){return db.$transaction(async tx=>{await active(tx,branchId);await tx.$queryRawUnsafe('SELECT "id" FROM "SalesJob" WHERE "id"=$1 FOR UPDATE',id(record));const job=await find(tx,'salesJob',record,branchId);if(['STOPPED','COMPLETED'].includes(job.status))fail(409,'This job has ended. Create another range to fetch again.');let data;
 if(action==='pause')data={status:'PAUSED'};else if(action==='stop')data={status:'STOPPED',encryptedKey:null};else if(action==='resume')data={status:'QUEUED',availableAt:new Date(),retryCount:0,lastError:null};else if(action==='key')data={encryptedKey:apiKey(body.apiKey),status:'PAUSED',lastError:null,retryCount:0};else fail(400,'Unknown action.');return jobView(await tx.salesJob.update({where:{id:job.id},data}));});},
 async leads(listId,branchId,query={}){const list=await find(db,'salesList',listId,branchId);const page=id(query.page||1),search=String(query.search||'').trim().slice(0,100);const where={listId:list.id};if(query.status){if(!statuses.includes(query.status))fail(400,'Invalid lead status.');where.status=query.status;}if(search){where.OR=[{name:{contains:search,mode:'insensitive'}},{phone:{contains:search}},{email:{contains:search,mode:'insensitive'}}];const mc=Number(search.replace(/^MC[- ]*/i,''));if(Number.isSafeInteger(mc)&&mc>0)where.OR.push({mc});}const [items,total]=await Promise.all([db.salesLead.findMany({where,orderBy:{mc:'asc'},skip:(page-1)*50,take:50}),db.salesLead.count({where})]);return {list,items,total,page};},
 async export(listId,branchId,messageTemplate){const list=await find(db,'salesList',listId,branchId);return {filename:'MC-'+list.startMc+'-to-MC-'+list.endMc+'.csv',csv:leadsCsv(await db.salesLead.findMany({where:{listId:list.id},orderBy:{mc:'asc'},take:1000}),messageTemplate)};},
 async detail(record,branchId){const lead=await find(db,'salesLead',record,branchId);return {...lead,contacts:await db.salesContact.findMany({where:{leadId:lead.id},orderBy:{createdAt:'desc'},take:50})};},
 async reviews(record,branchId,page=1){await find(db,'salesJob',record,branchId);return db.salesReview.findMany({where:{jobId:id(record)},orderBy:{mc:'asc'},skip:(id(page)-1)*50,take:50});},
 async update(record,branchId,body){if(!statuses.includes(body.status)||typeof body.notes!=='string'||body.notes.length>4000|| (body.followUpDate&&!/^\d{4}-\d{2}-\d{2}$/.test(body.followUpDate)))fail(400,'Check status, notes (4,000 characters maximum) and follow-up date.');return db.$transaction(async tx=>{await active(tx,branchId);const row=await find(tx,'salesLead',record,branchId);const changed=await tx.salesLead.updateMany({where:{id:row.id,revision:id(body.revision)},data:{status:body.status,notes:body.notes,followUpDate:body.followUpDate||null,revision:{increment:1}}});if(!changed.count)fail(409,'Another user updated this lead. Reopen it before saving.');return tx.salesLead.findUnique({where:{id:row.id}});});},
 async contact(record,branchId,user,requestId,undo=false){if(typeof requestId!=='string'||!/^[a-f0-9-]{36}$/i.test(requestId))fail(400,'Invalid contact action ID.');return db.$transaction(async tx=>{await active(tx,branchId);await tx.$queryRawUnsafe('SELECT "id" FROM "SalesLead" WHERE "id"=$1 FOR UPDATE',id(record));const lead=await find(tx,'salesLead',record,branchId);const event=await tx.salesContact.findUnique({where:{id:requestId}});if(event&&event.leadId!==lead.id)fail(409,'Contact action already belongs to another lead.');if(undo){if(!event)fail(404,'Contact action not found.');if(event.userId!==user.id&&!['ADMIN','MANAGER'].includes(user.role))fail(403,'Only the original user or a manager can undo this action.');if(!event.undoneAt)await tx.salesContact.update({where:{id:requestId},data:{undoneAt:new Date()}});}else if(!event){await tx.salesContact.create({data:{id:requestId,leadId:lead.id,userId:user.id,userName:user.name||'Staff'}});}const where={leadId:lead.id,undoneAt:null};const count=await tx.salesContact.count({where});const last=await tx.salesContact.findFirst({where,orderBy:{createdAt:'desc'}});return tx.salesLead.update({where:{id:lead.id},data:{contactCount:count,lastContactAt:last?.createdAt||null,revision:{increment:1}}});});}
 };
}
module.exports={createSalesService,id,jobView};
