const {createHash}=require('node:crypto');
function fail(status,message){const e=new Error(message);e.status=status;throw e;}
function id(value){const n=Number(value);if(!Number.isSafeInteger(n)||n<1)fail(400,'Invalid branch or list.');return n;}
function uuid(value){if(typeof value!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(value))fail(400,'Invalid campaign identifier.');return value;}
function phone(value){if(typeof value!=='string'||!/^[+\d\s().-]+$/.test(value.trim()))return null;const compact=value.replace(/[\s().-]/g,'');const national=compact.replace(/^\+?1(?=\d{10}$)/,'');if(/^[2-9]\d{2}[2-9]\d{6}$/.test(national))return '+1'+national;return null;}
function template(value){if(typeof value!=='string'||!value.trim()||value.length>1600)fail(400,'Enter a message of 1 to 1,600 characters.');const t=value.trim();const unknown=t.replace(/{{\s*(company_name|mc_number)\s*}}/g,'');if(/[{}]/.test(unknown))fail(400,'Use only {{company_name}} and {{mc_number}} as placeholders.');return t;}
function recipients(leads,message,sender){const seen=new Set(),blocked=new Set(leads.filter(l=>l.status==='NOT_INTERESTED').map(l=>phone(l.phone)).filter(Boolean));return leads.map(lead=>{const number=phone(lead.phone),name=String(lead.name||'').trim();const content=message.replace(/{{\s*(company_name|mc_number)\s*}}/g,(_,token)=>token==='company_name'?name:String(lead.mc));let reason=null;if(!number)reason='Missing or invalid US/Canada phone number (extensions are not supported)';else if(number===sender)reason='Same as sending number';else if(blocked.has(number))reason='Phone belongs to a lead marked Not interested';else if(!name)reason='Company name missing';else if(content.length>1600)reason='Personalized message exceeds 1,600 characters';else if(seen.has(number))reason='Duplicate phone number in this list';if(!reason)seen.add(number);return {leadId:lead.id,mc:lead.mc,companyName:name,phone:number,content,status:reason?'SKIPPED':'READY',reason};});}
function reviewHash(value){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
function safeProviderError(status,body){const code=typeof body?.code==='string'&&/^[a-z0-9_-]{1,30}$/i.test(body.code)?` (code ${body.code})`:'';const messages={400:'Quo rejected the message or sender registration',401:'Quo API key was rejected',402:'Quo subscription or message credits need attention',403:'Quo permission or messaging limit prevented sending',404:'Quo could not find the sender or message',429:'Quo rate limit reached'};return (messages[status]||`Quo returned HTTP ${status}`)+code+'. Check the Quo account before resuming.';}
module.exports={fail,id,uuid,phone,template,recipients,reviewHash,safeProviderError};
