import axios from "axios";
import "./SalarySlipView.css";

const API = "http://localhost:5000/api";

function SalarySlipView({ slip, onClose, onSaved, isPreview = false }) {
  if (!slip) return null;

  const token = localStorage.getItem("token");

  const auth = {
    headers: { Authorization: `Bearer ${token}` }
  };

  const saveSlip = async () => {
    if (!isPreview || slip.id) {
      return slip;
    }

    const res = await axios.post(`${API}/salary-slips`, slip, auth);
    return res.data.slip;
  };

  const handleSave = async () => {
    try {
      await saveSlip();
      alert("Salary slip saved in history");
      if (onSaved) onSaved();
    } catch (error) {
      alert(error.response?.data?.message || "Failed to save salary slip");
    }
  };

  const handlePrint = async () => {
    try {
      await saveSlip();
      setTimeout(() => {
        window.print();
        if (onSaved) onSaved();
      }, 200);
    } catch (error) {
      alert(error.response?.data?.message || "Failed to save before print");
    }
  };

  return (
    <div className="slip-modal">
      <div className="slip-actions no-print">
        <button onClick={onClose}>Close / Edit</button>

        {isPreview && (
          <button onClick={handleSave}>Save to History</button>
        )}

        <button onClick={handlePrint}>
          Print / Save PDF
        </button>
      </div>

      <div className="salary-slip-print">
        <div className="slip-header">
          <img src="/logo.jpeg" alt="GML Logo" />
          <div>
            <h2>Salary Slip</h2>
            <p>Get Moving Logistics</p>
          </div>
        </div>

        <div className="slip-info">
          <div>
            <strong>Employee:</strong> {slip.employeeName}
          </div>
          <div>
            <strong>Designation:</strong> {slip.designation || "-"}
          </div>
          <div>
            <strong>CNIC:</strong> {slip.cnic || "-"}
          </div>
          <div>
            <strong>Salary Type:</strong> {slip.salaryType}
          </div>
          <div>
            <strong>Period:</strong>{" "}
            {new Date(slip.periodStart).toLocaleDateString()} -{" "}
            {new Date(slip.periodEnd).toLocaleDateString()}
          </div>
        </div>

        <table className="slip-table">
          <tbody>
            {slip.salaryType === "COMMISSION" && (
              <>
                <tr>
                  <td>Dispatch Company</td>
                  <td>{slip.dispatchCompany || "-"}</td>
                </tr>
                <tr>
                  <td>Dispatch Amount USD</td>
                  <td>${Number(slip.dispatchAmountUSD || 0).toFixed(2)}</td>
                </tr>
                <tr>
                  <td>Commission %</td>
                  <td>{slip.commissionPercent}%</td>
                </tr>
                <tr>
                  <td>Employee Share USD</td>
                  <td>${Number(slip.employeeShareUSD || 0).toFixed(2)}</td>
                </tr>
                <tr>
                  <td>USD Rate</td>
                  <td>{slip.usdRate}</td>
                </tr>
              </>
            )}

            {slip.salaryType === "FIXED" && (
              <tr>
                <td>Fixed Salary PKR</td>
                <td>{Number(slip.fixedSalaryPKR || 0).toFixed(0)}</td>
              </tr>
            )}

            <tr>
              <td>Gross Salary PKR</td>
              <td>{Number(slip.grossSalaryPKR || 0).toFixed(0)}</td>
            </tr>

            <tr>
              <td>Bonus PKR</td>
              <td>{Number(slip.bonus || 0).toFixed(0)}</td>
            </tr>

            <tr>
              <td>Loan Deduction</td>
              <td>{Number(slip.loanDeduction || 0).toFixed(0)}</td>
            </tr>

            <tr>
              <td>Advance Deduction</td>
              <td>{Number(slip.advanceDeduction || 0).toFixed(0)}</td>
            </tr>

            <tr>
              <td>Other Deduction</td>
              <td>{Number(slip.otherDeduction || 0).toFixed(0)}</td>
            </tr>

            <tr className="net-row">
              <td>Net Salary PKR</td>
              <td>{Number(slip.netSalaryPKR || 0).toFixed(0)}</td>
            </tr>
          </tbody>
        </table>

        {slip.notes && (
          <div className="slip-notes">
            <strong>Notes:</strong> {slip.notes}
          </div>
        )}

        <div className="slip-footer">
          <p>Generated by GML Portal</p>
          <p>Authorized Signature __________________</p>
        </div>
      </div>
    </div>
  );
}

export default SalarySlipView;