import {messageFields} from './messageFields';
import {API} from '../api';
﻿import {useCallback,useEffect,useState} from 'react';
import './QuoMessages.css';
const statusLabel={DRAFT:'Draft',RUNNING:'Sending',PAUSED:'Paused',STOPPED:'Stopped',COMPLETED:'Finished',READY:'Queued',SENDING:'Submitting',ACCEPTED:'Accepted by Quo',FAILED:'Rejected',UNKNOWN:'Needs review',SKIPPED:'Skipped'};
export default function QuoMessages({branch}){
 const user=JSON.parse(localStorage.getItem('user')||'{}'),allowed=['ADMIN','MANAGER'].includes(user.role),editable=allowed&&branch.isActive;
 const [data,setData]=useState({connection:null,lists:[],campaigns:[],worker:{online:false}}),[key,setKey]=useState(''),[sender,setSender]=useState(''),[listPage,setListPage]=useState(1);
 const [form,setForm]=useState({name:'',listId:'',template:''}),[preview,setPreview]=useState(null),[requestId,setRequestId]=useState(null),[campaign,setCampaign]=useState(null),[page,setPage]=useState(1),[confirmed,setConfirmed]=useState(false),[history,setHistory]=useState(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const request=useCallback(async(path='',options={})=>{const r=await fetch(API_URL()+path+(path.includes('?')?'&':'?')+'branchId='+branch.id,{...options,headers:{Authorization:'Bearer '+localStorage.getItem('token'),'Content-Type':'application/json'}});let body;try{body=await r.json();}catch{throw new Error('Unable to read the server response. Please retry.');}if(!r.ok)throw new Error(body.message||'Unable to complete the request.');return body;},[branch.id]);
 const refresh=useCallback(async()=>{const next=await request('?listPage='+listPage);setData(next);},[request,listPage]);
 useEffect(()=>{if(!allowed)return;let alive=true;const update=()=>request('?listPage='+listPage).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});update();const timer=setInterval(()=>{if(!document.hidden)update();},10000);return()=>{alive=false;clearInterval(timer);};},[request,listPage,allowed]);
 useEffect(()=>{if(!campaign?.id)return;let alive=true;const update=()=>request('/campaigns/'+campaign.id+'?page='+page).then(c=>{if(alive)setCampaign(c);}).catch(e=>{if(alive)setError(e.message);});const timer=setInterval(()=>{if(!document.hidden)update();},10000);return()=>{alive=false;clearInterval(timer);};},[campaign?.id,page,request]);
 const act=async fn=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const change=e=>{setForm(p=>({...p,[e.target.name]:e.target.value}));setPreview(null);setRequestId(null);};
 const post=(path,body)=>request(path,{method:'POST',body:JSON.stringify({...body,branchId:branch.id})});
 async function view(id,p=1){await act(async()=>{setCampaign(await request('/campaigns/'+id+'?page='+p));setPage(p);setConfirmed(false);setHistory(null);});}
 async function control(action){await act(async()=>{setCampaign(await post('/campaigns/'+campaign.id+'/control',{action,reviewHash:campaign.reviewHash,confirmed:action==='start'?confirmed:true}));setConfirmed(false);await refresh();});}
 const total=campaign?Object.values(campaign.counts).reduce((a,n)=>a+n,0):0;
 if(!allowed)return <div className="sales-card"><h2>List messaging</h2><p>An administrator or manager can configure Quo and send list messages.</p></div>;
 return <div className="bulk-messages"><header className="bulk-heading"><div><span className="bulk-eyebrow">SALES OUTREACH</span><h1>Message a sales list</h1><p>Write once. Personalize for each company. Send from your Quo sales number.</p></div><span className={'bulk-badge '+(data.worker.online?'online':'')}>{data.worker.online?'Background sender online':'Sender offline'}</span></header>
 {error&&<p role="alert" className="bulk-error">{error}</p>}{notice&&<p role="status" className="bulk-notice">{notice}</p>}{!branch.isActive&&<p>This historical branch is read-only.</p>}
 <div className="bulk-steps"><span>1 · Your Quo number</span><span>2 · List & message</span><span>3 · Review & send</span></div>
 <div className="bulk-columns"><section className="bulk-card"><h2>1. Sending settings</h2>{data.connection&&<p className="bulk-connected">Connected sender: <strong>{data.connection.sender}</strong><br/><small>API key saved privately on the server.</small></p>}<form onSubmit={e=>{e.preventDefault();act(async()=>{const c=await post('/connection',{apiKey:key,sender});setKey('');setPreview(null);setNotice('Quo sender verified and saved. No message was sent.');setSender(c.sender);await refresh();});}}><label>Quo API key<input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} minLength={8} maxLength={512} required disabled={!editable||busy} placeholder={data.connection?'Paste a key only to update the connection':'Paste your Quo API key'}/></label><label>Your sending phone number<input type="tel" value={sender} onChange={e=>setSender(e.target.value)} required disabled={!editable||busy} placeholder={data.connection?.sender||'+1 202 555 0100'}/></label><button disabled={!editable||busy||!key.trim()}>{busy?'Please wait...':'Verify & save sender'}</button><p className="bulk-muted">Use a number in your Quo account. Saving checks the number and does not send a text.</p></form></section>
 <section className="bulk-card"><h2>2. List & message</h2><form onSubmit={e=>{e.preventDefault();act(async()=>{setPreview(await post('/preview',form));setRequestId(crypto.randomUUID());});}}><label>Campaign name<input name="name" value={form.name} onChange={change} maxLength={120} required disabled={!editable||busy} placeholder="Example: October dispatch introduction"/></label><label>Existing sales list<select name="listId" value={form.listId} onChange={change} required disabled={!editable||busy}><option value="">Choose a fetched list</option>{data.lists.map(l=><option key={l.id} value={l.id}>MC-{l.startMc} to MC-{l.endMc} · {l.count} leads · Range #{l.jobId}</option>)}</select></label><div className="bulk-actions"><button type="button" disabled={listPage===1||busy} onClick={()=>{setListPage(p=>p-1);setForm(p=>({...p,listId:''}));setPreview(null);}}>Previous lists</button><small>List page {listPage}</small><button type="button" disabled={data.lists.length<100||busy} onClick={()=>{setListPage(p=>p+1);setForm(p=>({...p,listId:''}));setPreview(null);}}>Next lists</button></div><label>Message template<textarea name="template" value={form.template} onChange={change} rows={6} maxLength={1600} required disabled={!editable||busy} placeholder={'Hi {{company_name}}, this is EAST WEST LOGISTICS LLC. ...'}/></label><div className="bulk-actions">{messageFields.map(([token,label])=><button type="button" key={token} disabled={!editable||busy} onClick={()=>{setForm(p=>({...p,template:p.template+'{{'+token+'}}'}));setPreview(null);}}>+ {label}</button>)}<small>{form.template.length}/1,600 characters</small></div><p className="bulk-muted">Each recipient gets a separate personalized SMS. State is derived from the physical address. Missing message fields, missing/invalid numbers, duplicates, and Not interested leads are skipped.</p><button className="bulk-primary" disabled={!editable||busy||!data.connection}>Preview personalized messages</button></form></section></div>
 {preview&&<section className="bulk-card"><h2>3. Review this list</h2><div className="bulk-counts"><span><strong>{preview.total}</strong> leads in list</span><span><strong>{preview.ready}</strong> ready to send</span><span><strong>{preview.skipped}</strong> skipped</span></div><p>Sending from <strong>{preview.sender}</strong>. First {preview.recipients.length} recipients shown below. Save the draft to review every recipient before sending. The draft freezes the current list; leads fetched later are not added.</p><div className="bulk-preview-grid">{preview.recipients.map(r=><article key={r.leadId}><strong>{r.companyName}</strong><small>MC-{r.mc} · {r.phone||'No valid number'}</small><p>{r.content}</p>{r.reason&&<small className="bulk-reason">{r.reason}</small>}</article>)}</div><button className="bulk-primary" disabled={!editable||busy||!preview.ready} onClick={()=>act(async()=>{const c=await post('/campaigns',{...form,requestId,reviewHash:preview.reviewHash});setCampaign(c);setPage(1);setConfirmed(false);setPreview(null);setNotice('Draft saved. Review the recipients below, then press Send.');await refresh();})}>Save draft & review all recipients</button><small className="bulk-muted">This step does not send messages.</small></section>}
 <section className="bulk-card"><div className="bulk-heading"><h2>Campaigns</h2><button disabled={busy} onClick={()=>act(refresh)}>Refresh</button></div>{!data.campaigns.length?<p>No campaigns yet. Choose a list and write your first message above.</p>:data.campaigns.map(c=><div className="bulk-campaign" key={c.id}><div><strong>{c.name}</strong><small>{c.sender} · {new Date(c.createdAt).toLocaleString()}</small></div><span className="bulk-badge">{statusLabel[c.status]}</span><button disabled={busy} onClick={()=>view(c.id)}>Open</button></div>)}<small className="bulk-muted">Latest 50 campaigns in this branch.</small></section>
 {campaign&&<section className="bulk-card"><div className="bulk-heading"><div><h2>{campaign.name}</h2><p>From {campaign.sender} · {statusLabel[campaign.status]}</p></div><button disabled={busy} onClick={()=>view(campaign.id,page)}>Refresh progress</button></div>{campaign.lastError&&<p className="bulk-error">{campaign.lastError}</p>}<div className="bulk-counts">{Object.entries(campaign.counts).map(([s,n])=><span key={s}><strong>{n}</strong>{statusLabel[s]}</span>)}</div><p className="bulk-muted">Accepted by Quo means submitted successfully, not confirmed delivered. Use Messages / status to check Quo. Unknown submissions are never automatically resent.</p>
 {editable&&campaign.status==='DRAFT'&&<div className="bulk-send-confirm"><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have reviewed the personalized message and recipients. Send these {campaign.counts.READY||0} individual texts from {campaign.sender}.</label><button className="bulk-primary" disabled={busy||!confirmed||!data.worker.online} onClick={()=>control('start')}>Send {campaign.counts.READY||0} messages</button><small>Quo API messaging charges apply. The queued campaign continues in the background after this page closes, at most one message every 10 seconds.</small></div>}
 <div className="bulk-actions">{editable&&campaign.status==='RUNNING'&&<button disabled={busy} onClick={()=>control('pause')}>Pause remaining messages</button>}{editable&&campaign.status==='PAUSED'&&<button disabled={busy} onClick={()=>control('resume')}>Resume remaining messages</button>}{editable&&['DRAFT','RUNNING','PAUSED'].includes(campaign.status)&&<button disabled={busy} onClick={()=>{if(window.confirm('Stop remaining messages? Already submitted messages cannot be recalled.'))control('stop');}}>Stop campaign</button>}</div><p className="bulk-muted">Pause and stop affect queued messages; a request already in progress may finish.</p>
 <div className="bulk-table"><table><thead><tr><th>Company / MC</th><th>Phone</th><th>Personalized message</th><th>Outcome</th><th>Quo</th></tr></thead><tbody>{campaign.recipients.map(r=><tr key={r.id}><td>{r.companyName}<small>MC-{r.mc}</small></td><td>{r.phone||'Unavailable'}</td><td><details><summary>View message</summary><p>{r.content}</p></details></td><td>{statusLabel[r.status]}{r.reason&&<small>{r.reason}</small>}{r.providerStatus&&<small>Quo: {r.providerStatus}</small>}</td><td><button disabled={busy||!r.phone} onClick={()=>act(async()=>{const result=await request('/campaigns/'+campaign.id+'/recipients/'+r.id+'/messages');setHistory({...result,name:r.companyName});})}>Messages / status</button></td></tr>)}</tbody></table></div><div className="bulk-actions"><button disabled={busy||page<=1} onClick={()=>view(campaign.id,page-1)}>Previous recipients</button><small>Page {page} · {total} recipients</small><button disabled={busy||page*50>=total} onClick={()=>view(campaign.id,page+1)}>Next recipients</button></div>
 {history&&<aside className="bulk-history"><div className="bulk-heading"><h3>Recent Quo messages · {history.name}</h3><button onClick={()=>setHistory(null)}>Close</button></div>{history.messages.length?history.messages.map(m=><article key={m.id}><small>{m.direction==='incoming'?'Received':'Outgoing'} · {m.status} · {new Date(m.createdAt).toLocaleString()}</small><p>{m.text||'[Non-text message]'}</p></article>):<p>No messages found.</p>}<small>Up to 20 recent messages. Refresh with Messages / status to see new replies.{history.hasMore?' Older messages are available in Quo.':''}</small></aside>}
 </section>}
 </div>;
}
function API_URL(){return API+'/quo';}
