import {useState} from 'react';
import './QuoMessages.css';
const samples=[
 {id:'demo-1',name:'Summit Freight · Demo',mc:'102401',phone:'+12025550101',equipment:'Dry van',trucks:8,unread:true,done:false,messages:[{direction:'outgoing',text:'Hi Alex, thanks for speaking with us. What lanes are you looking for this week?',time:'10:24 AM'},{direction:'incoming',text:'We have two trucks available in Dallas on Monday. Do you cover the Midwest?',time:'10:28 AM'}]},
 {id:'demo-2',name:'Blue Ridge Transport · Demo',mc:'102402',phone:'+12025550102',equipment:'Reefer',trucks:3,unread:true,done:false,messages:[{direction:'incoming',text:'Can you send me some information about your dispatch services?',time:'9:45 AM'}]},
 {id:'demo-3',name:'Oakline Carriers · Demo',mc:'102403',phone:'+12025550103',equipment:'Flatbed',trucks:5,unread:false,done:true,messages:[{direction:'outgoing',text:'Thank you for your time. We will follow up next week as requested.',time:'Yesterday'}]}
];
export default function QuoMessages({branch}){
 const [threads,setThreads]=useState(()=>structuredClone(samples)),[selected,setSelected]=useState('demo-1'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[drafts,setDrafts]=useState({}),[notice,setNotice]=useState('');
 const thread=threads.find(t=>t.id===selected),draft=drafts[selected]||'';
 const visible=threads.filter(t=>(filter==='all'||filter==='unread'&&t.unread||filter==='open'&&!t.done||filter==='done'&&t.done)&&`${t.name} ${t.mc} ${t.phone}`.toLowerCase().includes(search.toLowerCase()));
 const update=patch=>setThreads(previous=>previous.map(t=>t.id===selected?{...t,...patch}:t));
 function choose(t){setSelected(t.id);setNotice('');setThreads(previous=>previous.map(p=>p.id===t.id?{...p,unread:false}:p));}
 function previewSend(e){e.preventDefault();if(!draft.trim()||!branch.isActive)return;update({done:false,unread:false,messages:[...thread.messages,{direction:'outgoing',text:draft.trim(),time:'Just now · Preview only'}]});setDrafts(p=>({...p,[selected]:''}));setNotice('Added to this sample conversation. No SMS was sent.');}
 return <div className="quo-workspace"><header className="quo-heading"><div><span className="quo-eyebrow">SALES COMMUNICATIONS</span><h1>Messages</h1><p>Your conversations, alongside your carrier leads.</p></div><span className="quo-preview-badge">Quo · Visual preview</span></header>
 <div className="quo-demo-note"><strong>Preview with fictional contacts</strong><span>Explore the inbox and try a reply. Quo is not connected, and no messages leave this preview. Changes reset when you leave this tab.</span></div>
 {!branch.isActive&&<p role="status">This historical branch is read-only.</p>}
 <div className="quo-inbox"><aside className="quo-conversations" aria-label="Conversations"><div className="quo-list-head"><h2>Inbox <span>{threads.length}</span></h2><label>Search conversations<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Company, MC or phone"/></label><div className="quo-filters" aria-label="Conversation filters">{[['all','All'],['unread','Unread'],['open','Open'],['done','Done']].map(([v,l])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{l}</button>)}</div></div>
 <div className="quo-thread-list">{visible.map(t=><button className={'quo-thread '+(selected===t.id?'selected':'')} key={t.id} aria-pressed={selected===t.id} onClick={()=>choose(t)}><span className="quo-avatar">{t.name.slice(0,1)}</span><span className="quo-thread-copy"><strong>{t.name}</strong><span>{t.messages.at(-1).text}</span><small>MC-{t.mc} · {t.done?'Done':'Open'}</small></span>{t.unread&&<span className="quo-dot" aria-label="Unread"/>}</button>)}{!visible.length&&<p className="quo-empty">No conversations match this view.</p>}</div><div className="quo-inbox-foot">Sample inbox · {branch.branchName}</div></aside>
 <section className="quo-chat" aria-label="Selected conversation"><header className="quo-chat-head"><div><h2>{thread.name}</h2><span>{thread.phone} · {thread.done?'Done':'Open'}</span></div><button disabled={!branch.isActive} onClick={()=>update({done:!thread.done})}>{thread.done?'Reopen preview':'Mark preview done'}</button></header><div className="quo-timeline"><div className="quo-date">Sample conversation</div>{thread.messages.map((m,i)=><article key={i} className={'quo-bubble '+m.direction}><p>{m.text}</p><small>{m.direction==='outgoing'?'You · ':''}{m.time}</small></article>)}</div>
 <form className="quo-composer" onSubmit={previewSend}><label htmlFor="quo-reply">Reply preview</label><textarea id="quo-reply" disabled={!branch.isActive} value={draft} maxLength={1600} onChange={e=>setDrafts(p=>({...p,[selected]:e.target.value}))} placeholder="Type a sample reply to see how it will look..."/><div className="quo-composer-bottom"><small>{draft.length} characters · Preview only</small><button className="quo-send" disabled={!branch.isActive||!draft.trim()}>Preview reply →</button></div>{notice&&<p role="status" className="quo-notice">{notice}</p>}</form></section>
 <aside className="quo-details" aria-label="Contact details"><span className="quo-avatar large">{thread.name.slice(0,1)}</span><h2>{thread.name}</h2><span className="quo-contact-tag">Sample carrier</span><dl><dt>MC number</dt><dd>{thread.mc}</dd><dt>Phone</dt><dd>{thread.phone}</dd><dt>Equipment</dt><dd>{thread.equipment}</dd><dt>Reported trucks</dt><dd>{thread.trucks}</dd><dt>Conversation</dt><dd>{thread.done?'Done':'Open'}</dd></dl><div className="quo-connection"><strong>Quo connection</strong><p>Not connected in this preview.</p><p>The live version will use your Quo number for outgoing messages and show incoming replies here.</p></div><small className="quo-fine-print">Recipient selection and message templates will be added after we review this layout.</small></aside></div></div>;
}
