import { useCallback, useContext, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import Layout from '../components/Layout';
import { BranchContext } from '../context/BranchContext';
import { API } from '../api';
import PartnerDocument from '../contracts/PartnerDocument';
import '../contracts/contracts.css';
import '../contracts/partners.css';
const auth = () => ({headers:{Authorization:'Bearer '+localStorage.getItem('token')}});
const errorText = e => e.response?.data?.message || 'Unable to connect. Please try again.';
const initial = {companyName:'EASTWESTLOGISTICSLLC',managerName:'',silentName:'',managerEmail:'',silentEmail:'',address:'5 Hillcrest Dr, Downingtown, PA 19335',effectiveDate:new Date().toLocaleDateString('en-CA'),formationStatus:'PLANNED',formationDate:'',entityNumber:'',payoutDays:'',filingCosts:'',contributions:'',additionalTerms:''};
function BranchPartners({branch}) {
 const [form,setForm]=useState(initial),[items,setItems]=useState([]),[record,setRecord]=useState(null),[draft,setDraft]=useState(null),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[cancelId,setCancelId]=useState(null),[identity,setIdentity]=useState(null);
 const refresh=useCallback(async () => { const {data}=await axios.get(API+'/partner-agreements',{...auth(),params:{branchId:branch.id}});setItems(data); },[branch.id]);
 useEffect(()=>{let active=true;axios.get(API+'/partner-agreements',{...auth(),params:{branchId:branch.id}}).then(({data})=>{if(active)setItems(data);}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[branch.id]);
 const run=async fn=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const change=e=>{setForm(p=>({...p,[e.target.name]:e.target.value}));setDraft(null);setReviewed(false);};
 async function preview(e){e.preventDefault();await run(async()=>{const {data}=await axios.post(API+'/partner-agreements/preview',form,auth());setDraft(data);setRecord(null);setIdentity(null);setReviewed(false);});}
 async function create(){await run(async()=>{const {data}=await axios.post(API+'/partner-agreements',{...form,branchId:branch.id,reviewed,documentHash:draft.documentHash},auth());setRecord(data);setDraft(null);setReviewed(false);setNotice('Two private signing links created. Share each link only with its designated partner.');await refresh();});}
 const load=recordId=>run(async()=>{const {data}=await axios.get(API+'/partner-agreements/'+recordId,{...auth(),params:{branchId:branch.id}});setRecord(data);setIdentity(null);setDraft(null);});
 async function copy(role){const url=window.location.origin+'/partner-agreement/'+record.links[role];try{await navigator.clipboard.writeText(url);setNotice('Private signing link copied.');}catch{setNotice('Select and copy the link shown below.');}}
 async function passport(role){await run(async()=>{const {data,headers}=await axios.get(`${API}/partner-agreements/${record.id}/passport/${role}`,{...auth(),params:{branchId:branch.id},responseType:'blob'});const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=headers['content-disposition']?.match(/filename="([^"]+)"/)?.[1]||`passport-${role}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 return <div className="contracts-page partner-page"><nav className="partner-tabs"><Link to="/contracts">Carrier agreements</Link><Link to="/partner-agreements" aria-current="page">Partner agreements</Link></nav>
 <h2>Partner agreements</h2><p>Pennsylvania · Two members · Dispatch-only economic interests</p>
 {error&&<p role="alert" className="contract-error">{error}</p>}{notice&&<p role="status" className="contract-notice">{notice}</p>}
 <div className="partner-summary"><div><strong>85%</strong><span>Managing member<br/>Office, team and dispatch</span></div><div><strong>15%</strong><span>Silent member<br/>Dispatch income only</span></div><div><strong>$112.50</strong><span>Silent member's share of $1,000 collected<br/>After the 25% dispatcher allocation</span></div></div>
 {branch.isActive&&<section className="contract-card"><h3>Create a partner agreement</h3><p>This is LLC membership with restricted dispatching economics. A Pennsylvania attorney and tax adviser should review the arrangement before signing.</p><form onSubmit={preview}><fieldset disabled={busy} className="partner-fieldset"><div className="contract-grid">
 {['companyName','managerName','silentName','managerEmail','silentEmail','address'].map(name=><label key={name}>{({companyName:'Exact LLC legal name',managerName:'Managing member full legal name (85%)',silentName:'Silent member full legal name (15%)',managerEmail:'Managing member notice email',silentEmail:'Silent member notice email',address:'Business address'})[name]}<input name={name} value={form[name]} onChange={change} type={name.includes('Email')?'email':'text'} maxLength={name==='address'?400:200} required/></label>)}
 <label>Effective date<input type="date" name="effectiveDate" value={form.effectiveDate} onChange={change} required/></label>
 <label>LLC status<select name="formationStatus" value={form.formationStatus} onChange={change}><option value="PLANNED">Still to be formed</option><option value="FORMED">Already formed in Pennsylvania</option></select></label>
 <label>{form.formationStatus==='PLANNED'?'Formation deadline':'Formation date'}<input type="date" name="formationDate" value={form.formationDate} onChange={change} required/></label>
 {form.formationStatus==='FORMED'&&<label>Pennsylvania entity number<input name="entityNumber" value={form.entityNumber} onChange={change} required maxLength={80}/></label>}
 <label>Pay within calendar days of cleared receipt<input type="number" name="payoutDays" min="1" max="90" value={form.payoutDays} onChange={change} required/></label>
 <label>Who bears formation and filing costs?<select name="filingCosts" value={form.filingCosts} onChange={change} required><option value="">Select a partner</option><option value="MANAGER">Managing member (85%)</option><option value="SILENT">Silent member (15%)</option></select></label>
 </div><label>Initial contributions and commitments<textarea name="contributions" value={form.contributions} onChange={change} required maxLength={2500} rows={3} placeholder="Describe each member's agreed cash, services or other contributions, including any amounts and due dates."/></label>
 <label>Additional agreed terms (optional)<textarea name="additionalTerms" value={form.additionalTerms} onChange={change} maxLength={5000} rows={3}/></label>
 <button type="submit">{busy?'Please wait...':'Preview agreement'}</button></fieldset></form></section>}
 {draft&&<><PartnerDocument record={draft}/><section className="contract-card"><label className="partner-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I have reviewed the full wording, names and commercial terms. Create two signing links for this exact document.</label><p>Issued wording cannot be edited. Corrections require cancellation and a new agreement.</p><button disabled={busy||!reviewed} onClick={create}>Create both signing links</button></section></>}
 <section className="contract-card"><div className="partner-heading"><h3>Agreements</h3><button disabled={busy} onClick={()=>run(refresh)}>Refresh</button></div>{!items.length?<p>No partner agreements in this branch.</p>:items.map(item=><div key={item.id} className="partner-list-row"><div><strong>{item.managerName} &amp; {item.silentName}</strong><p>#{item.id} · {item.status.replaceAll('_',' ')} · {new Date(item.createdAt).toLocaleDateString()}</p></div><button disabled={busy} onClick={()=>load(item.id)}>Open</button></div>)}<small>Showing the latest 200 agreements.</small></section>
 {record&&<><section className="contract-card"><div className="partner-heading"><h3>Private signing links</h3><button disabled={busy} onClick={()=>load(record.id)}>Refresh signatures</button></div><p>Share one link with each designated partner. Each submits their own passport or driving licence and signs independently. Links do not expire; signing closes after signing, rejection, cancellation or branch archival.</p>
 {['manager','silent'].map(role=><div className="partner-link" key={role}><label>{record.settings[role+'Name']} · {role==='manager'?'85% managing member':'15% silent member'}<input aria-label={`${role} signing link`} readOnly value={window.location.origin+'/partner-agreement/'+record.links[role]}/></label><button onClick={()=>copy(role)}>Copy link</button></div>)}
 {branch.isActive&&['PENDING','PARTIALLY_SIGNED'].includes(record.status)&&<button className="partner-cancel" disabled={busy} onClick={()=>setCancelId(record.id)}>Cancel agreement</button>}
 {cancelId===record.id&&<div role="alert"><p>Cancel both signing links? Existing receipts remain recorded, but this agreement cannot be completed.</p><button disabled={busy} onClick={()=>run(async()=>{await axios.post(`${API}/partner-agreements/${record.id}/cancel`,{branchId:branch.id},auth());setRecord({...record,status:'CANCELLED'});setCancelId(null);await refresh();})}>Confirm cancellation</button> <button onClick={()=>setCancelId(null)}>Keep agreement</button></div>}
 </section><PartnerDocument record={record}/><section className="contract-card"><h3>Private identity records · Administrators only</h3><p>Identity document scans are encrypted in storage and excluded from shared agreements. Downloads contain sensitive personal data.</p>{['manager','silent'].filter(role=>record.signatures[role]).map(role=><div className="partner-actions" key={role}><strong>{record.settings[role+'Name']}</strong><button disabled={busy} onClick={()=>run(async()=>{const {data}=await axios.get(`${API}/partner-agreements/${record.id}/identity/${role}`,{...auth(),params:{branchId:branch.id}});setIdentity({...data,role});})}>Show identity details</button><button disabled={busy} onClick={()=>passport(role)}>Download private scan</button></div>)}{identity&&<p>{identity.documentType === 'DRIVING_LICENSE' ? 'Driving licence' : 'Passport'}: {identity.number} · {identity.country} <button onClick={()=>setIdentity(null)}>Hide</button></p>}</section></>}
 </div>;
}
export default function PartnerAgreements(){const {selectedBranch,branchError}=useContext(BranchContext);return <Layout title="Contracts"><>{selectedBranch?<BranchPartners key={selectedBranch.id} branch={selectedBranch}/>:<p>{branchError||'Loading branch...'}</p>}</></Layout>;}
