import {messageFields} from '../sales/messageFields';
import {Link,useSearchParams} from 'react-router-dom';
import QuoMessages from '../sales/QuoMessages';
﻿import {useCallback,useContext,useEffect,useState} from 'react';
import Layout from '../components/Layout';
import {BranchContext} from '../context/BranchContext';
import {API} from '../api';
import './SalesDepartment.css';
const labels={NEW:'New',CONTACTED:'Contacted',INTERESTED:'Interested',FOLLOW_UP:'Follow up',NOT_INTERESTED:'Not interested'};
const number=v=>Number(v||0).toLocaleString();
function SalesWorkspace({branch}){
 const user=JSON.parse(localStorage.getItem('user')||'{}'),manage=['ADMIN','MANAGER'].includes(user.role),editable=branch.isActive;
 const [data,setData]=useState({jobs:[],lists:[],worker:null}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [includeMessage,setIncludeMessage]=useState(false),[exportMessage,setExportMessage]=useState('Hi {{company_name}}, we offer dispatch services for carriers in {{state_name}}.');
 const [savedExport,setSavedExport]=useState(null),[exportReady,setExportReady]=useState(false),[listContactRequests,setListContactRequests]=useState({});
 const [jobPage,setJobPage]=useState(1),[listPage,setListPage]=useState(1);
 const [apiKey,setKey]=useState(''),[startMc,setStart]=useState(''),[endMc,setEnd]=useState('');
 const [listId,setList]=useState(null),[rows,setRows]=useState({items:[],total:0}),[page,setPage]=useState(1),[search,setSearch]=useState(''),[status,setStatus]=useState('');
 const [lead,setLead]=useState(null),[review,setReview]=useState(null),[reviewPage,setReviewPage]=useState(1),[replaceJob,setReplaceJob]=useState(null),[replacement,setReplacement]=useState('');
 const request=useCallback(async(path='?jobPage='+jobPage+'&listPage='+listPage,options={})=>{const r=await fetch(API+'/sales'+path+(path.includes('?')?'&':'?')+'branchId='+branch.id,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+localStorage.getItem('token')}});if(!r.ok){let message='Request failed.';try{message=(await r.json()).message||message;}catch{/* Use the generic message for a non-JSON response. */}throw new Error(message);}return r;},[branch.id,jobPage,listPage]);
 useEffect(()=>{let alive=true;request('/export-preference').then(r=>r.json()).then(value=>{if(alive){setSavedExport(value);setIncludeMessage(value.enabled);if(value.messageTemplate)setExportMessage(value.messageTemplate);setExportReady(true);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[branch.id]);
 async function saveExport(){await act(async()=>{const value=await request('/export-preference',{method:'PUT',body:JSON.stringify({messageTemplate:exportMessage,enabled:includeMessage})}).then(r=>r.json());setSavedExport(value);setNotice('Export message saved for this branch. Future downloads use this setting.');});}
 async function doneList(list){let requestId=listContactRequests[list.id];if(!requestId){if(!window.confirm('Add one contact to every current lead in this list? Existing contact counts increase by one; statuses stay unchanged.'))return;requestId=crypto.randomUUID();setListContactRequests(previous=>({...previous,[list.id]:requestId}));}await act(async()=>{const result=await request('/lists/'+list.id+'/contact',{method:'POST',body:JSON.stringify({requestId})}).then(r=>r.json());setListContactRequests(previous=>{const next={...previous};delete next[list.id];return next;});await refresh();if(listId===list.id)await loadRows();setNotice('List marked done: one contact added to '+result.leadCount+' leads.');});}
 async function refresh(){setData(await request().then(r=>r.json()));}
 async function loadRows(){if(listId)setRows(await request('/lists/'+listId+'/leads?page='+page+'&search='+encodeURIComponent(search)+'&status='+status).then(r=>r.json()));}
 useEffect(()=>{let alive=true;const update=()=>request().then(r=>r.json()).then(d=>{if(alive){setData(d);setLoading(false);}}).catch(e=>{if(alive){setError(e.message);setLoading(false);}});update();const timer=setInterval(()=>{if(!document.hidden)update();},5000);return()=>{alive=false;clearInterval(timer);};},[request]);
 useEffect(()=>{if(!listId)return;let alive=true;request('/lists/'+listId+'/leads?page='+page+'&search='+encodeURIComponent(search)+'&status='+status).then(r=>r.json()).then(d=>{if(alive)setRows(d);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[request,listId,page,search,status]);
 async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function create(e){e.preventDefault();await act(async()=>{await request('/jobs',{method:'POST',body:JSON.stringify({branchId:branch.id,startMc:Number(startMc),endMc:Number(endMc),apiKey})});setKey('');setNotice('Range and API key saved. The entry field is cleared for privacy; the worker uses the saved key.');await refresh();});}
 async function control(job,action){if(action==='stop'&&!window.confirm('Stop this range permanently? Saved leads remain available. Use Pause if you want to resume later.'))return;await act(async()=>{await request('/jobs/'+job.id+'/'+action,{method:'POST',body:'{}'});await refresh();});}
 async function openLead(id){await act(async()=>setLead(await request('/leads/'+id).then(r=>r.json())));}
 function preserveDraft(next){setLead(previous=>previous?.id===next.id?{...next,notes:previous.notes,status:previous.status,followUpDate:previous.followUpDate}:next);}
 async function done(item){const requestId=crypto.randomUUID();await act(async()=>{await request('/leads/'+item.id+'/contact',{method:'POST',body:JSON.stringify({requestId})});await loadRows();if(lead?.id===item.id)preserveDraft(await request('/leads/'+item.id).then(r=>r.json()));setNotice('Contact recorded.');});}
 async function exportList(list){await act(async()=>{const blob=await request('/lists/'+list.id+'/export',savedExport?.enabled?{method:'POST',body:JSON.stringify({messageTemplate:savedExport.messageTemplate})}:{}).then(r=>r.blob());const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='MC-'+list.startMc+'-to-MC-'+list.endMc+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 async function openReviews(job,p=1){await act(async()=>{const items=await request('/jobs/'+job.id+'/reviews?page='+p).then(r=>r.json());setReview({job,items});setReviewPage(p);});}
 const total=data.totals||data.jobs.reduce((a,j)=>{for(const k of ['processed','accepted','excluded','missing','needsReview','duplicates'])a[k]=(a[k]||0)+j[k];return a;},{});
 const online=data.worker?.online;
 return <div className="sales-workspace">
 <section className="sales-hero"><div><span className="sales-eyebrow">CARRIER PROSPECTING</span><h1>Sales Department</h1><p>Turn MC ranges into organized freight leads and track every conversation.</p></div><span className={'sales-pill '+(online?'good':'')}>{online?(data.worker.hosted?'Background scheduler online':'Local worker online (PC must stay on)'):'Worker not connected'}</span></section>
 {error&&<div className="sales-alert" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<p className="sales-notice" role="status">{notice}</p>}
 {!editable&&<p className="sales-alert">This historical branch is read-only.</p>}
 <div className="sales-stats">{[['processed','MCs checked'],['accepted','Qualified leads'],['excluded','Excluded'],['needsReview','Needs review']].map(([key,label])=><article key={key}><span>{label}</span><strong>{number(total[key])}</strong></article>)}</div>
 <div className="sales-columns"><section className="sales-card"><h2>Start a new range</h2><p>We check US carrier authority and freight categories, and save up to 1,000 unique qualified MCs per list.</p>
 {manage&&editable?<form onSubmit={create}><label>SaferWebAPI key<input type="password" autoComplete="new-password" value={apiKey} onChange={e=>setKey(e.target.value)} required minLength={8} maxLength={512} placeholder="Paste your API key here"/></label><div className="sales-fields"><label>Starting MC<input type="number" min="1" max="99999999" required value={startMc} onChange={e=>setStart(e.target.value)} placeholder="e.g. 100000"/></label><label>Ending MC<input type="number" min={startMc||1} max="99999999" required value={endMc} onChange={e=>setEnd(e.target.value)} placeholder="e.g. 110000"/></label></div><button className="sales-primary" disabled={busy}>Start fetching</button><small>The field clears after saving; your saved job keeps the key. Use Replace API key on a range to change it. The key is encrypted on the server. Requests run no faster than once every two seconds; slower responses and rate limits reduce the speed.</small></form>:<p>An administrator or manager can start and control fetching.</p>}
 </section><section className="sales-card"><h2>Fetch results</h2><div className="sales-chart" aria-label="Carrier classification totals">{[['accepted','Qualified'],['excluded','Excluded'],['needsReview','Review'],['missing','Not found'],['duplicates','Already saved']].map(([key,label])=><div className="sales-bar-row" key={key}><span>{label}</span><div><i style={{width:((total[key]||0)/Math.max(1,total.processed||0)*100)+'%'}}/></div><b>{number(total[key])}</b></div>)}</div><p className="sales-muted">Garbage, refuse, hay, farm supplies, grain/feed and livestock carriers are excluded, even when they also carry general freight. Email and equipment are only shown when supplied; equipment type cannot be confirmed from cargo alone.</p></section></div>
 <section className="sales-card"><h2>Fetching activity</h2>{loading?<p>Loading jobs...</p>:!data.jobs.length?<div className="sales-empty">No ranges yet. Enter your API key and MC range above to begin.</div>:data.jobs.map(job=><article className="sales-job" key={job.id}><div className="sales-row"><div><strong>MC-{job.startMc} to MC-{job.endMc}</strong><p>{number(job.processed)} / {number(job.endMc-job.startMc+1)} checked &middot; {number(job.accepted)} leads &middot; Next MC: {job.nextMc<=job.endMc?job.nextMc:'Complete'}</p></div><span className="sales-pill">{job.status}</span></div><small>{job.hasKey?"API key saved for this range":"API key removed because this range has ended"}</small><progress max={job.endMc-job.startMc+1} value={job.processed}/>{job.lastError&&<p className="sales-error">{job.lastError}</p>}<div className="sales-actions">{manage&&editable&&!['STOPPED','COMPLETED'].includes(job.status)&&<>{['QUEUED','RUNNING'].includes(job.status)?<button disabled={busy} onClick={()=>control(job,'pause')}>Pause</button>:<button disabled={busy} onClick={()=>control(job,'resume')}>Resume</button>}<button disabled={busy} onClick={()=>{setReplaceJob(job);setReplacement('');}}>Replace API key</button><button disabled={busy} onClick={()=>control(job,'stop')}>Stop range</button></>}{job.needsReview>0&&<button disabled={busy} onClick={()=>openReviews(job)}>Review {number(job.needsReview)} uncertain records</button>}<details><summary>Exclusion and processing details</summary>{Object.entries(job.reasons||{}).map(([reason,count])=><p key={reason}>{reason}: {number(count)}</p>)}<p>API attempts: {number(job.requests)} &middot; Retries on current MC: {job.retryCount}</p></details></div></article>)}<div className="sales-actions"><button disabled={jobPage<=1} onClick={()=>setJobPage(jobPage-1)}>Previous ranges</button><span>Page {jobPage}</span><button disabled={jobPage*20>=data.jobCount} onClick={()=>setJobPage(jobPage+1)}>Next ranges</button></div></section>
 <section className="sales-card"><h2>Personalized CSV messages</h2><p>Add a ready-to-copy message immediately after Phone in your Excel-compatible CSV.</p><label className="sales-export-toggle"><input type="checkbox" disabled={!exportReady||busy||!editable} checked={includeMessage} onChange={e=>setIncludeMessage(e.target.checked)}/> Include Message column in downloads</label>{includeMessage&&<><label>Custom export message<textarea disabled={!exportReady||busy||!editable} rows={5} maxLength={1600} value={exportMessage} onChange={e=>setExportMessage(e.target.value)}/></label><div className="sales-actions">{messageFields.map(([token,label])=><button type="button" disabled={!exportReady||busy||!editable} key={token} onClick={()=>setExportMessage(value=>value+'{{'+token+'}}')}>+ {label}</button>)}</div><small>{exportMessage.length}/1,600 characters. State comes from the physical address. Missing fields are flagged when downloading; remove those fields or download without messages. No messages are sent by downloading.</small></>}<div className="sales-actions"><button className="sales-primary" disabled={!exportReady||busy||!editable} onClick={saveExport}>Save export message</button><small>{!exportReady?'Loading saved message...':savedExport?.messageTemplate===exportMessage&&savedExport?.enabled===includeMessage?'Saved for this branch': 'Unsaved changes - downloads use your last saved settings.'}</small></div><p className="sales-muted">Your saved message and inclusion setting stay available across sessions and devices. Use Download CSV on a list below. Messages appear only in the file.</p></section>
 <section className="sales-card"><div className="sales-row"><h2>Lead lists</h2><span>Up to 1,000 qualified MCs per list</span></div>{!data.lists.length?<div className="sales-empty">Your first list will appear as qualifying carriers are found.</div>:<div className="sales-list-grid">{data.lists.map(list=><article key={list.id} className={listId===list.id?'selected':''}><small>RANGE #{list.jobId} / LIST {list.ordinal}</small><h3>MC-{list.startMc} &ndash; MC-{list.endMc}</h3><p>{list.count} / 1,000 leads {list.count<1000?'(partial list)':''}</p><div className="sales-actions"><button onClick={()=>{setList(list.id);setPage(1);setSearch('');setStatus('');}}>Open list</button><button disabled={busy||!exportReady} onClick={()=>exportList(list)}>Download CSV</button><button disabled={busy||!editable||!list.count} onClick={()=>doneList(list)}>{listContactRequests[list.id]?'Retry list Done':'List Done '+(list._count?.contactBatches||0)+' - mark all +1'}</button></div></article>)}</div>}<div className="sales-actions"><button disabled={listPage<=1} onClick={()=>setListPage(listPage-1)}>Previous lists</button><span>Page {listPage}</span><button disabled={listPage*20>=data.listCount} onClick={()=>setListPage(listPage+1)}>Next lists</button></div></section>
 {listId&&<section className="sales-card"><div className="sales-row"><h2>MC-{rows.list?.startMc} &ndash; MC-{rows.list?.endMc}</h2><button disabled={busy} onClick={()=>act(loadRows)}>Refresh leads</button></div><div className="sales-fields"><label>Search company, MC, phone or email<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div><div className="sales-table"><table><thead><tr><th>MC / Company</th><th>Contact</th><th>Address</th><th>Trucks*</th><th>Status</th><th>Contact count</th></tr></thead><tbody>{rows.items.map(item=><tr key={item.id}><td><button className="sales-link" onClick={()=>openLead(item.id)}>{item.name}</button><small>MC-{item.mc} / USDOT {item.usdot}</small></td><td>{item.phone||'Not provided'}<small>{item.email||'Email not provided'}</small></td><td>{item.address}</td><td>{item.details.powerUnits??'Unknown'}</td><td>{labels[item.status]}</td><td><button disabled={busy||!editable} onClick={()=>done(item)}>Done {item.contactCount} &middot; +1</button></td></tr>)}</tbody></table></div>{!rows.items.length&&<p>No leads match this view.</p>}<div className="sales-row"><small>*Reported power units; ownership and equipment are not confirmed.</small><div className="sales-actions"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} &middot; {number(rows.total)} leads</span><button disabled={page*50>=rows.total} onClick={()=>setPage(page+1)}>Next</button></div></div></section>}
 {lead&&<div className="sales-overlay"><section className="sales-dialog" role="dialog" aria-modal="true" aria-label="Lead details"><div className="sales-row"><h2>{lead.name}</h2><button onClick={()=>setLead(null)}>Close</button></div>{error&&<p className="sales-alert" role="alert">{error}</p>}<p>MC-{lead.mc} / USDOT {lead.usdot}</p><dl>{[['DBA',lead.details.dba],['Address',lead.address],['Mailing address',lead.details.mailingAddress],['Phone',lead.phone],['Email',lead.email],['Reported power units',lead.details.powerUnits],['Drivers',lead.details.drivers],['Authority',lead.details.operatingStatus],['Cargo',lead.details.cargo.join(', ')],['Equipment',lead.details.equipment],['Safety rating',lead.details.safetyRating],['Source updated',lead.details.sourceUpdatedAt],['Fetched',new Date(lead.fetchedAt).toLocaleString()]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v??'Not provided'}</dd></div>)}</dl>{lead.details.sourceUrl&&<a href={lead.details.sourceUrl} target="_blank" rel="noreferrer">View source snapshot</a>}<form onSubmit={e=>{e.preventDefault();act(async()=>{await request('/leads/'+lead.id,{method:'PATCH',body:JSON.stringify(lead)});setLead(await request('/leads/'+lead.id).then(r=>r.json()));await loadRows();setNotice('Lead saved.');});}}><div className="sales-fields"><label>Status<select disabled={!editable} value={lead.status} onChange={e=>setLead({...lead,status:e.target.value})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Follow-up date<input disabled={!editable} type="date" value={lead.followUpDate||''} onChange={e=>setLead({...lead,followUpDate:e.target.value})}/></label></div><label>Notes<textarea disabled={!editable} maxLength={4000} value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})}/></label><button className="sales-primary" disabled={busy||!editable}>Save lead</button></form><h3>Contact history &middot; Done {lead.contactCount}</h3><button disabled={busy||!editable} onClick={()=>done(lead)}>Mark another contact done</button>{lead.contacts.map(c=><div className="sales-history" key={c.id}><span>{c.userName} &middot; {new Date(c.createdAt).toLocaleString()} {c.undoneAt?'(undone)':''}</span>{!c.undoneAt&&editable&&(manage||c.userId===user.id)&&<button disabled={busy} onClick={()=>act(async()=>{await request('/leads/'+lead.id+'/undo',{method:'POST',body:JSON.stringify({requestId:c.id})});preserveDraft(await request('/leads/'+lead.id).then(r=>r.json()));await loadRows();})}>Undo</button>}</div>)}</section></div>}
 {review&&<div className="sales-overlay"><section className="sales-dialog" role="dialog" aria-modal="true" aria-label="Uncertain carriers"><div className="sales-row"><h2>Needs review</h2><button onClick={()=>setReview(null)}>Close</button></div>{error&&<p className="sales-alert" role="alert">{error}</p>}<p>These records are held separately and are not included in qualified lists.</p>{review.items.map(r=><article className="sales-job" key={r.id}><strong>MC-{r.mc} &middot; {r.details.name}</strong><p>{r.reason}</p><small>{r.details.address} &middot; {r.details.operatingStatus}</small>{r.details.sourceUrl&&<p><a href={r.details.sourceUrl} target="_blank" rel="noreferrer">View source</a></p>}</article>)}<div className="sales-actions"><button disabled={busy||reviewPage<=1} onClick={()=>openReviews(review.job,reviewPage-1)}>Previous</button><span>Page {reviewPage}</span><button disabled={busy||reviewPage*50>=review.job.needsReview} onClick={()=>openReviews(review.job,reviewPage+1)}>Next</button></div></section></div>}
 {replaceJob&&<div className="sales-overlay"><form className="sales-dialog" onSubmit={e=>{e.preventDefault();act(async()=>{await request('/jobs/'+replaceJob.id+'/key',{method:'POST',body:JSON.stringify({apiKey:replacement})});setReplacement('');setReplaceJob(null);setNotice('API key replaced. Press Resume when ready.');await refresh();});}}><h2>Replace API key</h2>{error&&<p className="sales-alert" role="alert">{error}</p>}<label>New API key<input type="password" autoComplete="new-password" required minLength={8} value={replacement} onChange={e=>setReplacement(e.target.value)}/></label><div className="sales-actions"><button disabled={busy}>Save key and pause</button><button type="button" onClick={()=>{setReplaceJob(null);setReplacement('');}}>Cancel</button></div></form></div>}
 </div>;
}
export default function SalesDepartment(){const {selectedBranch}=useContext(BranchContext);const [params]=useSearchParams();const messages=params.get('view')==='messages';return <Layout title="Sales Department"><nav className="sales-section-tabs" aria-label="Sales Department sections"><Link to="/sales" aria-current={!messages?'page':undefined}>Carrier leads</Link><Link to="/sales?view=messages" aria-current={messages?'page':undefined}>List messaging</Link></nav>{selectedBranch&&(messages?<QuoMessages key={selectedBranch.id} branch={selectedBranch}/>:<SalesWorkspace key={selectedBranch.id} branch={selectedBranch}/>)}</Layout>;}
